### PR TITLE
json2junit.py: Fix `undefined symbol` error

### PR DESCRIPTION
**Pull request by mardy**

### CODE REVIEW

**Comment by sashko** [comment]
@mardy may we ask you to add this script to our yocto.groovy? we've had tests broken on Jenkins for a while now, and nobody has time to fix this. Thanks!

**Comment by mardy** [comment]
Sure, just please explain a bit more what yocto-groovy is (or where I can find more info about it), as the name doesn't ring a bell to me :-)

**Comment by sashko** [comment]
The script should be executed somewhere [here](https://github.com/Pelagicore/pelux-manifests/blob/master/ci-scripts/yocto.groovy#L117) and then the name of the file with results should be corrected, so we copy the right file.

**Comment by mardy** [comment]
Here we go: https://github.com/Pelagicore/pelux-manifests/pull/370

**Pull request merged**
